### ISSUE TITLE
签退如何选择时间呢

### ISSUE THREAD

**Issue by Danyhug** [5ime/xyb_auto_sign#1]
RT

**Comment by 5ime** [comment]
签退时间取决于你的定时任务，我是使用 `crontab` 设置的定时任务，直接每天 `8:00` 和 `17:00` 运行脚本
```
php xyb.php
```
另外为了可以正常签退，我在代码中限制了距离 `签到` 时间 **9小时**后再次运行脚本是即为 `签退`  操作

考虑的是8小时工作制加中午休息一个小时，当然你可以在代码中自行变更为你认为的合适间隔，代码如下

https://github.com/5ime/xyb_auto_sign/blob/9f104e9570c43c0a188e07a439217d39f07d275a/xyb.php#L75-L82

**Comment by Danyhug** [comment]
明白了，感谢
