### ISSUE TITLE
指定经纬度

### ISSUE THREAD

**Issue by hcnk3HrzQe** [5ime/xyb_auto_sign#3]
怎么才能指定经纬度？     谢谢

**Comment by 5ime** [comment]
无需指定会自动获取

**Comment by hcnk3HrzQe** [comment]
> 无需指定会自动获取

那怎么把自动获取的改成手动了  因为我想变成外勤  他那个是集中安排的，但是人不在那边

**Comment by 5ime** [comment]
> > 无需指定会自动获取
> 
> 那怎么把自动获取的改成手动了 因为我想变成外勤 他那个是集中安排的，但是人不在那边

https://github.com/5ime/xyb_auto_sign/blob/24fa76d999d562d2746438c13861603ed349ddc2/xyb.php#L57-L67

**Comment by hcnk3HrzQe** [comment]
> > > 无需指定会自动获取
> > 
> > 
> > 那怎么把主动夺取的改成手动了 因为我想变成外勤 他那个是集中安排的，但人不在那边
> 
> https://github.com/5ime/xyb_auto_sign/blob/24fa76d999d562d2746438c13861603ed349ddc2/xyb.php#L57-L67

```
$v['location']['lng'] = 120.1234;
$v['location']['lat'] = 30.5678;     
``` 
测试成功
